version: "3.8"

volumes:
  logs:
    driver: local

services:
  php:
    container_name: coconut-manager-be
    image: php_7_4
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/slim_app
      - logs:/var/www/slim_app/logs
    environment:
      - docker="true"
      - DB_DRIVER=mysql
      - DB_HOST=coconut-db
      - DB_NAME=coconu24_dev
      - DB_USERNAME=coconut
      - DB_PASSWORD=coconut
    depends_on:
      - db

  nginx:
    container_name: coconut-manager-nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8
    container_name: coconut-db
    restart: always
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - ./docker/db/seed/database_dev.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=coconut
