name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      #- name: Install dependencies
      #  run: composer install

      #- name: Run test suite
      #  run: composer test

      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag coconut-manager:$(date +%s)
        
      #- name: test ssh command
      #  run: ssh root@159.65.119.127 'pwd'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 159.65.119.127
          username: root
          password: ${{ secrets.MORIMAC }}
          port: 22
          script: whoami
