name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
    DOCKER_USER: morientes 
    DOCKER_PASSWORD: q1w2e3
    REPO_NAME: coconut-ai-manager
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Push
        run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}

      - name: executing remote ssh commands (run deploy script on server)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
              cd /opt/coconut
              source .profile
              export TAG_BE=${{ steps.date.outputs.date }}
              echo $TAG_BE > .profile
              echo $TAG_FE >> .profile
              sh ./deploy-be.sh


